import "server-only";

function str(name: string, def = ""): string {
  const v = process.env[name];
  return v === undefined || v === null ? def : String(v);
}

function num(name: string, def: number): number {
  const v = process.env[name];
  if (v === undefined || v === null || String(v).trim() === "") return def;
  const parsed = Number(v);
  return Number.isFinite(parsed) ? parsed : def;
}

function bool(name: string, def = false): boolean {
  const v = process.env[name];
  if (v === undefined || v === null) return def;
  return ["1", "true", "yes", "y", "on"].includes(String(v).trim().toLowerCase());
}

export const env = {
  // Qdrant
  QDRANT_URL: str("QDRANT_URL"),
  QDRANT_API_KEY: str("QDRANT_API_KEY") || undefined,
  QDRANT_TIMEOUT_SEC: num("QDRANT_TIMEOUT_SEC", 120),
  QDRANT_COLLECTION_NAME: str("QDRANT_COLLECTION_NAME", "documents"),
  QDRANT_VECTOR_SIZE: num("QDRANT_VECTOR_SIZE", 1536),
  QDRANT_VECTOR_NAME: str("QDRANT_VECTOR_NAME").trim() || null,
  QDRANT_AUTO_RECREATE_ON_DIMENSION_MISMATCH: bool("QDRANT_AUTO_RECREATE_ON_DIMENSION_MISMATCH", false),
  QDRANT_UPSERT_BATCH_SIZE: num("QDRANT_UPSERT_BATCH_SIZE", 64),
  QDRANT_UPSERT_RETRIES: num("QDRANT_UPSERT_RETRIES", 3),
  QDRANT_UPSERT_RETRY_BACKOFF_SEC: num("QDRANT_UPSERT_RETRY_BACKOFF_SEC", 1.0),

  // OpenRouter / LLM
  OPENROUTER_API_KEY: str("OPENROUTER_API_KEY") || undefined,
  OPENROUTER_BASE_URL: str("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
  OPENROUTER_REFERER: str("OPENROUTER_REFERER", "http://localhost:3000"),
  OPENROUTER_TITLE: str("OPENROUTER_TITLE", "chatbot-backend"),
  OPENROUTER_CHAT_MODEL: str("OPENROUTER_CHAT_MODEL", "google/gemini-2.5-flash"),
  OPENROUTER_EMBEDDING_MODEL: str("OPENROUTER_EMBEDDING_MODEL", "openai/text-embedding-3-small"),
  OPENROUTER_MAX_OUTPUT_TOKENS: num("OPENROUTER_MAX_OUTPUT_TOKENS", 1024),
  OPENROUTER_TEMPERATURE: num("OPENROUTER_TEMPERATURE", 0.3),
  OPENROUTER_HTTP_TIMEOUT_SEC: num("OPENROUTER_HTTP_TIMEOUT_SEC", 120),
  OPENROUTER_EMBEDDING_TIMEOUT_SEC: num("OPENROUTER_EMBEDDING_TIMEOUT_SEC", 180),
  OPENROUTER_EMBEDDING_MAX_RETRIES: num("OPENROUTER_EMBEDDING_MAX_RETRIES", 6),
  OPENROUTER_MAX_CONTINUATIONS: num("OPENROUTER_MAX_CONTINUATIONS", 1),
  OPENROUTER_SUMMARY_MODEL: str("OPENROUTER_SUMMARY_MODEL").trim() || null,
  OPENROUTER_SUMMARY_MAX_OUTPUT_TOKENS: num("OPENROUTER_SUMMARY_MAX_OUTPUT_TOKENS", 384),

  // RAG
  RAG_TOP_K: num("RAG_TOP_K", 6),
  RAG_SIMILARITY_THRESHOLD: num("RAG_SIMILARITY_THRESHOLD", 0.15),
  RAG_MAX_CONTEXT_TOKENS: num("RAG_MAX_CONTEXT_TOKENS", 3200),
  RAG_CANDIDATE_MULTIPLIER: num("RAG_CANDIDATE_MULTIPLIER", 2),
  RAG_LLM_FOCUSED_CONTEXT_CHUNKS: num("RAG_LLM_FOCUSED_CONTEXT_CHUNKS", 5),
  RAG_LLM_POST_SUMMARY: bool("RAG_LLM_POST_SUMMARY", false),
  RAG_SUMMARIZE_MIN_INPUT_CHARS: num("RAG_SUMMARIZE_MIN_INPUT_CHARS", 200),
  RAG_STRICT_MAX_SENTENCES: num("RAG_STRICT_MAX_SENTENCES", 5),
  RAG_INGEST_CHUNK_SIZE_TOKENS: num("RAG_INGEST_CHUNK_SIZE_TOKENS", 420),
  RAG_INGEST_CHUNK_OVERLAP_TOKENS: num("RAG_INGEST_CHUNK_OVERLAP_TOKENS", 80),
  EMBEDDING_BATCH_SIZE: num("EMBEDDING_BATCH_SIZE", 64),

  // Auth / JWT
  JWT_SECRET_KEY: str("JWT_SECRET_KEY", str("SECRET_KEY", "insecure-dev-secret-change-me")),
  JWT_ALGORITHM: str("JWT_ALGORITHM", "HS256"),
  JWT_ACCESS_TOKEN_LIFETIME_MIN: num("JWT_ACCESS_TOKEN_LIFETIME_MIN", 15),
  JWT_REFRESH_TOKEN_LIFETIME_DAYS: num("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 7),

  // Firebase
  FIREBASE_CREDENTIALS_PATH: str("FIREBASE_CREDENTIALS_PATH") || str("GOOGLE_APPLICATION_CREDENTIALS"),

  // Email (SMTP)
  EMAIL_HOST: str("EMAIL_HOST"),
  EMAIL_PORT: num("EMAIL_PORT", 587),
  EMAIL_HOST_USER: str("EMAIL_HOST_USER"),
  EMAIL_HOST_PASSWORD: str("EMAIL_HOST_PASSWORD"),
  EMAIL_USE_TLS: bool("EMAIL_USE_TLS", true),
  DEFAULT_FROM_EMAIL: str("DEFAULT_FROM_EMAIL") || str("EMAIL_HOST_USER") || "no-reply@example.com",

  // Plans / limits
  FREE_PLAN_MAX_BOTS: num("FREE_PLAN_MAX_BOTS", 1),
  PAID_PLAN_MAX_BOTS: num("PAID_PLAN_MAX_BOTS", 10),
  SUPER_ADMIN_DASHBOARD_CACHE_TTL_SECONDS: num("SUPER_ADMIN_DASHBOARD_CACHE_TTL_SECONDS", 300),
  BOT_WORKSPACE_CACHE_TTL_SECONDS: num("BOT_WORKSPACE_CACHE_TTL_SECONDS", 60),
};

export type AppEnv = typeof env;
